### PR TITLE
Remove msg type

### PR DESCRIPTION
**Pull request by cnkarz**
- Remove `MsgType` field from `Connector`
- Rename `Unsubscribe` with `Close` in Subscription

### CODE REVIEW

**Comment by hugjobk** [comment]
I think we should change EventSink to a buffered channel. A non-buffered channel can cause other goroutines to block while trying to send messages to that channel.

**Comment by hugjobk** [comment]
We also need to write a benchmark to test the performance the Connector library and see how many messages per second it can send to Kafka.

**Comment by cnkarz** [comment]
> I think we should change EventSink to a buffered channel. A non-buffered channel can cause other goroutines to block while trying to send messages to that channel.

Can you elaborate more on that?

**Comment by cnkarz** [comment]
> We also need to write a benchmark to test the performance the Connector library and see how many messages per second it can send to Kafka.

I believe it is not a priority to optimize Kafka produce performance atm. But if you think it is important, can you create a ticket with the reasoning please?

**Review by wliang0 — APPROVED** [review]
looks good to me

**Pull request merged**
